"""
Django settings for moss project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h#)6ybvedpw%w@_i719^3(fe%5h9e76je2)$n(ulq$40z@rxi1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["moss-skillshare.herokuapp.com", "localhost"]

AUTH_USER_MODEL = "studentskillsharing.Profile"

# Application definition

AUTHENTICATION_BACKENDS = (
    'social_core.backends.open_id.OpenIdAuth', # } 
    'social_core.backends.google.GoogleOpenId',# } need these too
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '458830468440-ebr7igk1lnnb123n3tffh06ehbvq73kn.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'g7l7BpJ7F6Q3kW520QfdgikY'


INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'studentskillsharing.apps.StudentskillsharingConfig',
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'notifications',
    'social_django',
    'crispy_forms',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'moss.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
                'studentskillsharing.context_processors.add_photo_url_to_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'moss.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#######
# PLEASE DO NOT TOUCH -- THIS WHOLE STATEMENT <REQUIRED> FOR TRAVIS+HEROKU
#######
if 'TRAVIS' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'test_db',
            'USER': 'postgres',
            'PASSWORD': '',
            'HOST': 'localhost',
            'POST:': ''
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'd569aih4gf59c1',
            'USER': 'bwidaltsxchyfg', #'postgres',
            'PASSWORD': '31c8188ac5f185f146e3f7ca3e99f145f149aa91297a83267bf3393ae658fbc6',
            'HOST': 'ec2-54-235-159-101.compute-1.amazonaws.com',
            'PORT': '5432'
        }
    }


#DATABASES = {
#    
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'd569aih4gf59c1', #'moss_studentskillshare_database',
#        'USER': 'bwidaltsxchyfg', #'postgres',
#        'PASSWORD': '31c8188ac5f185f146e3f7ca3e99f145f149aa91297a83267bf3393ae658fbc6',#'moss3240',
#        'HOST': 'ec2-54-235-159-101.compute-1.amazonaws.com', #'localhost',
#        'PORT': '5432',
#        'TEST': {
#            'NAME': 'moss_studentskillshare_database',
#        },
#    }
#}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# AWS ACCESS INFORMATION
AWS_ACCESS_KEY_ID = 'AKIA334AD5ESP744H236'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'moss-static'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = 'static'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR,"staticfiles")
STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION) #STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = '/studentskillsharing/redirect_new_users/'
# NEW_USER_REDIRECT_URL = '/accounts/signup'

LOGOUT_REDIRECT_URL = '/'

SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_LOGIN_ERROR_URL = ''
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = ['virginia.edu']
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_EMAILS = ['sherriff@gmail.com', 'sherriff@virginia.edu']

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'moss.auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

CRISPY_TEMPLATE_PACK = 'bootstrap4'

django_heroku.settings(locals())
